text = input("Enter text:\n")

print(f" Третий символ - {text[2]}")
len = len(text)
print(f" Предпоследний символ - {text[len-2]}")
print(f" Первые пять символов - {text[:5]}")
print(f" Все кроме 2 последних символов - {text[:len-2]}")
print(f" Парные индексы - {text[::2]}")
print(f" Непарные индексы - {text[1::2]}")
print(f" Обратный порядок - {text[::-1]}")
print(f" Обратный порядок через 1 - {text[::-2]}")
print(f" Длинна = {len} символов")
